
positive-boundary: 99984
negative-boundary: -99984
max-rank-all-item: 5
min-rank-all-item: 2
max-rank-item: 2
min-rank-item: 1
rank:
  Common: 50
  Rare: 30
  Mythical: 20
worlds:
  world: 500
